DROP TABLE IF EXISTS tunnels;

CREATE TABLE tunnels (
    id TEXT PRIMARY KEY,           -- UUID generated by our server or Cloudflare Tunnel ID
    name TEXT NOT NULL,            -- e.g., 'p1', 'p2'
    token TEXT NOT NULL,           -- The Cloudflare Tunnel token
    status TEXT NOT NULL DEFAULT 'AVAILABLE', -- 'AVAILABLE', 'BUSY'
    device_id TEXT,                -- The ID of the local CLI currently using it
    port INTEGER,                  -- Local port being forwarded
    protocol TEXT DEFAULT 'tcp',   -- 'tcp' or 'udp'
    last_heartbeat INTEGER,        -- Unix timestamp of the last heartbeat
    created_at INTEGER DEFAULT (cast(strftime('%s', 'now') as integer))
);

-- Fast lookup for available tunnels
CREATE INDEX idx_tunnels_status ON tunnels(status);

-- Fast lookup for checking specific devices
CREATE INDEX idx_tunnels_device ON tunnels(device_id);
