name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to cache
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: xpose-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=xpose-builder

  lint:
    name: Lint & Format
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load xpose-builder image from cache
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: xpose-builder:latest
          load: true # Tải image về local docker daemon
          cache-from: type=gha,scope=xpose-builder # Tải từ cache của GitHub Actions

      - name: Lint & Format
        shell: bash
        run: |
          docker run --rm -v $(pwd):/workspace xpose-builder:latest bash -c "cargo fmt --all -- --check && cargo clippy --all-targets --all-features -- -D warnings"

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load xpose-builder image from cache
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: xpose-builder:latest
          load: true # Tải image về local docker daemon
          cache-from: type=gha,scope=xpose-builder # Tải từ cache của GitHub Actions

      - name: Run Tests
        shell: bash
        run: |
          docker run --rm -v $(pwd):/workspace xpose-builder:latest cargo test --workspace
